### ISSUE TITLE
mcrypt is deprecated, so remove 'encrypt' in database functionality

### ISSUE THREAD

**Issue by ChangePlaces** [jordansamuel/PASTE#106]
it was deprecated in 7.1 or 7.2 and if the 'encrypt' checkbox is checked, the paste silently errors out causing user confusion

**Comment by xdedeone** [comment]
maybe this be useful
the encryption Paste uses is MCRYPT_RIJNDAEL_256 - turns out, it's an insecure encryption, so I changed it to MCRYPT_RIJNDAEL_128 (which is actually more secure, as the 256 version isn't really 256 anyway).
now it works.

**Comment by jgdye** [comment]
It's actually a problem that mcrypt is being used at all. For php 7.2 and above, it has to be manually compiled and installed on most distros, and there is no guarantee that it will be available at all going forward.  If changing to another library is not feasible, it should at least allow the admin to disable encryption so that the user doesn't get an error with no explanation.

**Comment by robertfels** [comment]
includes/functions.php

CHANGE
```
function encrypt($value)
{
	$password = "MyOwnPassword";
	$encrypted_string=openssl_encrypt($value,"AES-256-CBC",$password);
	return $encrypted_string;
}

function decrypt($value)
{
	$password = "MyOwnPassword";
	$decrypted_string=openssl_decrypt($value,"AES-256-CBC",$password);
	return $decrypted_string;
}
```

**Comment by robertfels** [comment]
https://github.com/jordansamuel/PASTE/pull/112
