### ISSUE TITLE
Fatal error: Cannot redeclare str_contains() in G:\xampp\htdocs\paste\includes\functions.php on line 16

### ISSUE THREAD

**Issue by therealknight** [jordansamuel/PASTE#170]
`Fatal error: Cannot redeclare str_contains() in G:\xampp\htdocs\paste\includes\functions.php on line 16`

Receiving this error after installing locally on a XAMPP server.

**Comment by thinkverse** [comment]
This is a known breaking change issue with PHP 8. PHP added its own `str_contains` function into its standard library in PHP 8, and since PASTE also adds the function, it throws an error because a function cannot be redeclared in PHP. A fix for this is included in the PR (#172) I just opened.

https://github.com/jordansamuel/PASTE/blob/8d16af0173f73e4fd84743100b9f012459fc503a/includes/functions.php#L16

**Comment by thinkverse** [comment]
A fix for this issue has been merged, you can clone the latest changes if you want to hotfix your version. I would not recommend that though since PHP 8 is not currently fully supported by PASTE, I would recommend downgrading your server to either 7.3 or 7.4 until it's fully supported. 👍
